# Generated by Django 4.1.7 on 2023-02-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_signupcourses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcourses',
            name='course',
            field=models.CharField(choices=[('Python', 'Python'), ('HTML/CSS', 'HTML/CSS'), ('Reactjs', 'Reactjs'), ('Data Analysis', 'Data Analysis'), ('Data Science', 'Data Science'), ('Python Web', 'Python Web')], max_length=20),
        ),
    ]
